### ISSUE TITLE
ValueError: For training, each question should have exactly 1 answer.

### ISSUE THREAD

**Issue by RAXAI** [huggingface/pytorch-transformers#554]
Tried to run run_squad.py with the squad 2.0 dataset and came up with this error, ValueError: For training, each question should have exactly 1 answer. How do I solve this?

**Comment by rusiaaman** [comment]
Please give more information: the command used (arguments passed), traceback (the command line output), and version (can use `pip show pytorch_pretrained_bert`)

I faced a similar problem with `read_squad_examples` when passing `input_file=dev.json` and `is_training=True`.

**Comment by yifan** [comment]
I have this problem when training on SQUADv2 without `--version_2_with_negative` option. Basically for squad 2.0, it is possible there is no answer for questions.

**Comment by vikas95** [comment]
Hi,

I see the same error. Some of the questions have multiple answer spans. 

The error suggests that the current preprocessing codes cannot handle multiple answer spans for a given question.

 Has anyone fixed this ??

Thanks

**Comment by allenbkim** [comment]
I also receive this error when using the `--version_2_with_negative` flag paired with training data from SQuAD 2.0. It looks like it may be caused by some logic in `utils_squad.py`, lines 150-152; it seems that answerable questions are expected to only have one answer. I'm not familiar enough with the task and data set to know if this is a correct assumption, but since I'm using data from the SQuAD 2.0 web site I would think it should train fine.

**Comment by pohanchi** [comment]
For training, the assumption is true.

**Comment by allenbkim** [comment]
Thanks for clarifying!
