### ISSUE TITLE
Couldn't import '''BertPreTrainedModel'''

### ISSUE THREAD

**Issue by chenbingxiayu** [huggingface/pytorch-transformers#615]
I installed this lib by '''pip install pytorch-pretrained-bert''', and there are no problems when run the examples. However, when I import '''BertPreTrainedModel''', I use '''from pytorch_pretrained_bert import BertPreTrainedModel''', error occurs.
I want to write a new class like '''BertForSequenceClassification''', and in order to use the facility of constructing the instance of the class by "'from_pretrained('bert-base-uncased')''' . My new class need to inherit the class '''BertPreTrainedModel'''.
In another way, we need the config file to get the instance of the class like '''BertForSequenceClassification''', however, I couldn't find the file 'bert_config.json'.
Are there other ways to write a new class like '''BertForSequenceClassification'''?
Thanks all of you!

**Comment by eveliao** [comment]
I guess you have to clone the repository. You just need to add all the classes you want to import in this line:
https://github.com/huggingface/pytorch-pretrained-BERT/blob/3fc63f126ddf883ba9659f13ec046c3639db7b7e/pytorch_pretrained_bert/__init__.py#L12
Then you can install from source:
`pip install --editable .`

Of course since you download all the code, you can directly add your own class in `/pytorch_pretrained_bert/modeling_openai.py` then install from source.

**Comment by chenbingxiayu** [comment]
So sorry that I am not familiar with the lib installation in python. 
Thanks for your suggestions. I know how to solve it.

Best Regards,
Chen Bingyu
