### ISSUE TITLE
Invalid Syntax Error trying to run pregenerate_training_data.py

### ISSUE THREAD

**Issue by MNCTTY** [huggingface/pytorch-transformers#756]
I'm getting such error, can't understand what's wrong
![image](https://user-images.githubusercontent.com/37251686/60671996-072cfc00-9e7d-11e9-9b73-b8b1f01652c9.png)

Plus, is it possible to further fine tune once fine tuned model, that appears after simple finetuning .py in corresponding folder (pytorch_model.bin) ?

**Comment by thomwolf** [comment]
Your snippet is too short to see what type of error there is, can you extract a larger one?

**Comment by MNCTTY** [comment]
Hi 
yes
![image](https://user-images.githubusercontent.com/37251686/60735756-30bd5480-9f5d-11e9-940c-d39c73cb4084.png)

**Comment by abhishek0318** [comment]
F-strings were introduced in Python 3.6. Try using Python 3.6 and report if it helped.

**Comment by abhishek0318** [comment]
Pull the latest changes from master and report if that helps.

**Comment by MNCTTY** [comment]
it has been disappeared in pregenerate script, and appeared in finetuning on pregenerated data script
![image](https://user-images.githubusercontent.com/37251686/60804690-b708af00-a186-11e9-9e21-024e745c8bdf.png)

**Comment by abhishek0318** [comment]
You are getting these errors because you are using Python 3.5 and the code is making use of f-strings which are introduced in Python 3.6. You could try using Python 3.6 or change the source code replacing f-string with str.format syntax.

@thomwolf The readme says repository supports Python 3.5+. Does that mean Python 3.5 is supported as well? If yes, I think we should change f-strings for the format syntax.

**Comment by thomwolf** [comment]
Well, only the library code supports Python 3.5+, I don't check the examples which are mostly contributed by the community.
If you want to fix Python 3.5 support for the examples I'm happy to welcome a PR.
