### ISSUE TITLE
How to use   GPT2LMHeadModel  for conditional generation

### ISSUE THREAD

**Issue by rabeehk** [huggingface/pytorch-transformers#970]
Hi
could you please provide one single example on how to use   GPT2LMHeadModel  for conditional generation?
thanks
Rabeeh

**Comment by LysandreJik** [comment]
Hi Rabeeh,

Please take a look at the [run_generation.py](https://github.com/huggingface/pytorch-transformers/blob/master/examples/run_generation.py) example which shows how to do conditional generation with the library's auto-regressive models (GPT/GPT-2/Transformer-XL/XLNet).

**Comment by SaveTheBees-n-Seeds** [comment]
What's cracking Rabeeh, 

look, this code makes the trick for GPT2LMHeadModel.
But, as torch.argmax() is used to derive the next word; there is a lot of repetition.

`
from transformers import GPT2LMHeadModel, GPT2Tokenizer
import torch
import argparse
parser = argparse.ArgumentParser()
parser.add_argument('--input', type=str, help='Initial text for GPT2 model', required=True)
parser.add_argument('--length', type=int, help='Amount of new words added to input', required=True, default=20)
args = parser.parse_args()

tokenizer = GPT2Tokenizer.from_pretrained("gpt2")
model = GPT2LMHeadModel.from_pretrained('gpt2')

generated = tokenizer.encode(args.input)
context = torch.tensor([generated])
past = None

for i in range(args.length):
    #print("{}=>>{}".format(i,tokenizer.decode(generated)))
    output, past = model(context, past=past)
    token = torch.argmax(output[0, :])
    generated += [token.tolist()]
    context = token.unsqueeze(0)

sequence = tokenizer.decode(generated)

print("Final sequence =>>{}".format(sequence))
`

As LysandreJik pointed out, is better to clone the hugginface transformer repo in Git, and go to the examples ---they do it great.

**Comment by rabeehk** [comment]
Hi
Thank you very much, very helpful for me.

**Comment by Contributorrandom** [comment]
HI @SaveTheBees-n-Seeds ,
 I have a particular use case (which is somewhat related to this quest); 
 
 Context: instead of a text-to-condition, I have directly a  vector, which is an output from some other model (which is also learnable ). 
 In this context, how to do conditional fine-tuning of the GPT-2 model. From the GPT-2 model's perspective, we can think that the dataset to train is a **list of tuples of the form (condition_vec,text_sample)**. But note that condition_vec is an output from some other model that is also involved in the optimisation.

 One naive approach is to feed this vector directly as the context vector (Assume dimensions match). 
 Will it work? (I could test it soon)
 Or is there any better solution?
